### ISSUE TITLE
Push replication with attachments fails with CDTDatastore pod 0.19.0

### ISSUE THREAD

**Issue by mkistler** [cloudant-labs/CDTIncrementalStore#13]
Changes to CDTDatastore in version 0.19.0 cause push replications for documents with "follows" attachments to hang.  Version 0.19.1 has the same problem.

Need to lock dependency on CDTDatastore to version 0.18.0 for now until a new version is available that fixed this problem.

**Comment by mkistler** [comment]
The new version of CDTDatastore (0.19.2) should fix this problem.

**Comment by tfrank64** [comment]
Are we going to merge your fix or look into version 0.19.2 as a fix?

**Comment by mkistler** [comment]
I'm going to try moving up to 19.2.  It should work, just need to verify.
